[package]
name = "ptools"
version.workspace = true
edition.workspace = true

[build-dependencies]
winresource = { version = "0.1.31", default-features = false }

[dependencies]
ptools-core.workspace = true
ptools-ui.workspace = true
serde_json.workspace = true
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Controls", "Win32_UI_Controls_Dialogs", "Win32_UI_Shell", "Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_System_Com", "Win32_UI_HiDpi", "Win32_Graphics_Dwm", "Win32_System_Registry", "Win32_Storage_FileSystem", "Win32_Security", "Win32_System_Memory", "Win32_System_DataExchange", "Win32_System_Pipes"] }
